default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USER', 'admin') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'admin') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: store_development

test:
  <<: *default
  database: shop_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch('DB_NAME', 'shop_production') %>
  cache:
    <<: *primary_production
    database: shop_production_cache
    migrations_paths: db/cache_migrate
