default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USER', 'admin') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'admin') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: store_development

test:
  <<: *default
  database: shop_test

production:
  <<: *default
  database: shop_production

  cable:
    adapter: postgresql
    database: shop_production_cable
    host: <%= ENV.fetch('DB_HOST', 'localhost') %>
    username: <%= ENV.fetch('DB_USER', 'admin') %>
    password: <%= ENV.fetch('DB_PASSWORD', 'admin') %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
